# Project information
site_name: Global Azure 2022 Workshop
site_url: https://jmaitrehenry.github.io/ga2022
site_author: Julien Maitrehenry & Simon Bernier

# Repository
repo_name: Global Azure 2022 Workshop
repo_url: https://github.com/jmaitrehenry/ga2022
edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome:
    - About the workshop: README.md
  - Workshop:
    - Pre-work - Install Docker: lab-0/README.md
    - Lab 1 - Build and push our containers to Azure Container Registry: lab-1/README.md
    - Lab 2 - Deploy our app using Azure Container Apps: lab-2/README.md
    - Lab 3 - Automate app building and deployment using Github Action to Azure Container Apps: lab-3/README.md
  # - Workshop Azure Kubernetes Service:
  #   - Lab 4 - Creating a Kubernetes Cluster using Azure AKS: lab-4/README.md
  #   - Lab 5 - Configuring an Ingress Controller using nginx and Let's Encrypt: lab-5/README.md
  #   - Lab 6 - Deploy our application into AKS using Github Action: lab-6/README.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2022 Julien Maitrehenry & Simon Bernier

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: blue
    accent: blue

plugins:
  - search
  - mkdocs-video

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmaitrehenry
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jmaitrehenry/

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde